// src/main/java/com/twintransition/energy/dto/OptimizationRecommendation.java
package com.twintransition.energy.dto;

public record OptimizationRecommendation(
        String actionableScript, // e.g., "HVAC_Office_X: set_temp=22C, time=15:00-17:00"
        String naturalLanguageJustification, // Generated by Gemini
        double estimatedCostSavingsEur,
        double estimatedCarbonFootprintReductionKgCO2,
        String recommendationId
) {}